<javaelement>
	<package>
		java.lang.reflect
	</package>
	<type>
		<name>
			public class InvocationTargetException  extends ReflectiveOperationException
		</name>
		<description>
			InvocationTargetException is a checked exception that wraps an exception thrown by an invoked method or constructor. As of release 1.4, this exception has been retrofitted to conform to the general purpose exception-chaining mechanism. The "target exception" that is provided at construction time and accessed via the getTargetException() method is now known as the cause, and may be accessed via the Throwable.getCause() method, as well as the aforementioned "legacy method."
		</description>
		<methods>
			<method>
				<name>
					protected InvocationTargetException()
				</name>
				<description>
					Constructs an InvocationTargetException with null as the target exception.
				</description>
				
			</method>
			<method>
				<name>
					public InvocationTargetException(Throwable target)
				</name>
				<description>
					Constructs a InvocationTargetException with a target exception.
				</description>
				
			</method>
			<method>
				<name>
					public InvocationTargetException(Throwable target,                           String s)
				</name>
				<description>
					Constructs a InvocationTargetException with a target exception and a detail message.
				</description>
				
			</method>
			<method>
				<name>
					public Throwable getTargetException()
				</name>
				<description>
					Get the thrown target exception. This method predates the general-purpose exception chaining facility. The Throwable.getCause() method is now the preferred means of obtaining this information.
				</description>
				
			</method>
			<method>
				<name>
					public Throwable getCause()
				</name>
				<description>
					Returns the cause of this exception (the thrown target exception, which may be null).
				</description>
				
			</method>
			
		</methods>
		
	</type>
	
</javaelement>
