<javaelement>
	<package>
		java.util.concurrent
	</package>
	<type>
		<name>
			public class ExecutionException  extends Exception
		</name>
		<description>
			Exception thrown when attempting to retrieve the result of a task that aborted by throwing an exception. This exception can be inspected using the Throwable.getCause() method.
		</description>
		<methods>
			<method>
				<name>
					protected ExecutionException()
				</name>
				<description>
					Constructs an ExecutionException with no detail message. The cause is not initialized, and may subsequently be initialized by a call to initCause.
				</description>
				
			</method>
			<method>
				<name>
					protected ExecutionException(String message)
				</name>
				<description>
					Constructs an ExecutionException with the specified detail message. The cause is not initialized, and may subsequently be initialized by a call to initCause.
				</description>
				
			</method>
			<method>
				<name>
					public ExecutionException(String message,                    Throwable cause)
				</name>
				<description>
					Constructs an ExecutionException with the specified detail message and cause.
				</description>
				
			</method>
			<method>
				<name>
					public ExecutionException(Throwable cause)
				</name>
				<description>
					Constructs an ExecutionException with the specified cause. The detail message is set to:     (cause == null ? null : cause.toString()) (which typically contains the class and detail message of cause).
				</description>
				
			</method>
			
		</methods>
		
	</type>
	
</javaelement>
