<javaelement>
	<package>
		java.util.concurrent
	</package>
	<type>
		<name>
			public class RejectedExecutionException  extends RuntimeException
		</name>
		<description>
			Exception thrown by an Executor when a task cannot be accepted for execution.
		</description>
		<methods>
			<method>
				<name>
					public RejectedExecutionException()
				</name>
				<description>
					Constructs a RejectedExecutionException with no detail message. The cause is not initialized, and may subsequently be initialized by a call to initCause.
				</description>
				
			</method>
			<method>
				<name>
					public RejectedExecutionException(String message)
				</name>
				<description>
					Constructs a RejectedExecutionException with the specified detail message. The cause is not initialized, and may subsequently be initialized by a call to initCause.
				</description>
				
			</method>
			<method>
				<name>
					public RejectedExecutionException(String message,                            Throwable cause)
				</name>
				<description>
					Constructs a RejectedExecutionException with the specified detail message and cause.
				</description>
				
			</method>
			<method>
				<name>
					public RejectedExecutionException(Throwable cause)
				</name>
				<description>
					Constructs a RejectedExecutionException with the specified cause. The detail message is set to:  (cause ==   null ? null : cause.toString()) (which typically contains the class and detail message of cause).
				</description>
				
			</method>
			
		</methods>
		
	</type>
	
</javaelement>
