<javaelement>
	<package>
		java.io
	</package>
	<type>
		<name>
			public class WriteAbortedException  extends ObjectStreamException
		</name>
		<description>
			Signals that one of the ObjectStreamExceptions was thrown during a write operation. Thrown during a read operation when one of the ObjectStreamExceptions was thrown during a write operation. The exception that terminated the write can be found in the detail field. The stream is reset to it's initial state and all references to objects already deserialized are discarded. As of release 1.4, this exception has been retrofitted to conform to the general purpose exception-chaining mechanism. The "exception causing the abort" that is provided at construction time and accessed via the public detail field is now known as the cause, and may be accessed via the Throwable.getCause() method, as well as the aforementioned "legacy field."
		</description>
		<methods>
			<method>
				<name>
					public Exception detail
				</name>
				<description>
					Exception that was caught while writing the ObjectStream. This field predates the general-purpose exception chaining facility. The Throwable.getCause() method is now the preferred means of obtaining this information.
				</description>
				
			</method>
			<method>
				<name>
					public WriteAbortedException(String s,                       Exception ex)
				</name>
				<description>
					Constructs a WriteAbortedException with a string describing the exception and the exception causing the abort.
				</description>
				
			</method>
			<method>
				<name>
					public String getMessage()
				</name>
				<description>
					Produce the message and include the message from the nested exception, if there is one.
				</description>
				
			</method>
			<method>
				<name>
					public Throwable getCause()
				</name>
				<description>
					Returns the exception that terminated the operation (the cause).
				</description>
				
			</method>
			
		</methods>
		
	</type>
	
</javaelement>
